name: Commandgo
version: 1.7.2
main: teacommontea.commandgo.Commandgo
api-version: '1.21'
author: teacommontea
description: WorldGuard-style command visibility/execution rules.
softdepend: [LuckPerms]
commands:
  commandgo:
    description: Manage Commandgo rules.
    usage: /commandgo help
    aliases: [cg, cmdgo, cmgo]
permissions:
  commandgo.admin:
    description: Manage Commandgo rules.
    default: op
